version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./data/db:/var/lib/postgresql/data
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5432 -U myuser -d mydb"]

      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 30s


  webapp:
    build: 
      context: ./ieee-website-app
      dockerfile: ../dockerfiles/frontend.dev.dockerfile
    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - '3000:3000'



