version: "3.8"

services:
  postgres:
    image: postgres
    # set shared memory limit when using docker-compose
    # shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    # volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      # change with env file
    # ports:
    #   - '5433:5432'

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5432 -U postgres -d postgres"]

      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 30s

    # networks:

  # test-db:
  #   build: ./db-testing

  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  nodejs-db-test:
    build: 
      context: ./nodejs-db-test
      dockerfile: Dockerfile

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - '3000:3000'

    

  # next-build:
  #   build:
  #     context: "./ieee-website-app"
  #     dockerfile: "../dockerfile/frontend.dev.docker"
  #     # using dev build



