version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  webapp:
    build: 
      context: ./ieee-website-app
      dockerfile: ../dockerfiles/frontend.dev.dockerfile
    volumes:
      - ./ieee-website-app/src:/app/src
      - ./ieee-website-app/public:/app/public
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@postgres:5432/mydb?schema=public"
      AUTH_SECRET: "JGIcRxLUOxcAqHe1NkaJJC8fW9gjj5IlvKNxpd6KFUw=" # Added by `npx auth`. Read more: https://cli.authjs.dev
    ports:
      - '3000:3000'



