version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: some-postgres
    restart: always
    ports:
      - "5433:5432"  # Mapping PostgreSQL to port 5433 on your local machine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres


volumes:
  postgres_data:
